from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path(
        "signup/",
        views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "verify-signup/",
        views.VerifySignupOTPView.as_view(),
        name="verify-signup",
    ),
    path(
        "signup-resend-otp/",
        views.ResendSignupOTPView.as_view(),
        name="resend-signup-otp",
    ),
    path(
        "login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path(
        "forgot-password/",
        views.ForgotPasswordView.as_view(),
        name="forgot-password",
    ),
    path(
        "forgot-password-verify/",
        views.VerifyForgotPasswordOTPView.as_view(),
        name="verify-forgot-password",
    ),
    path(
        "forgot-otp-resend/",
        views.ResendForgotPasswordOTPView.as_view(),
        name="resend-forgot-password",
    ),
    path(
        "reset-password/",
        views.ResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "change-password",
        views.ChangePasswordView.as_view(),
        name="change-password",
    ),
    path(
        "token/refresh/",
        views.TokenRefreshView.as_view(),
        name="token-refresh",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "role/",
        views.SwitchRoleView.as_view(),
        name="switch-role",
    ),
]
