# Generated by Django 6.1 on 2026-08-22 12:21

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.TextField()),
                ('property_type', models.CharField(max_length=100)),
                ('number_of_units', models.IntegerField()),
                ('rentable_area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year_built', models.IntegerField()),
                ('year_renovated', models.IntegerField(blank=True, null=True)),
                ('occupancy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parking_spaces', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('sponsor_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accounts.rolemodel')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Chat Session',
                'verbose_name_plural': 'Property Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.propertychatsession')),
            ],
            options={
                'verbose_name': 'Property Chat Message',
                'verbose_name_plural': 'Property Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=properties.models.property_file_upload_path)),
                ('category', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('image_source', models.CharField(blank=True, choices=[('map', 'From Map'), ('manual', 'Manual Upload')], default='manual', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='properties.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_property_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_files', to='accounts.rolemodel')),
            ],
            options={
                'verbose_name': 'Property File',
                'verbose_name_plural': 'Property Files',
                'ordering': ['category', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='properties.propertyfile')),
            ],
            options={
                'verbose_name': 'File Chunk',
                'verbose_name_plural': 'File Chunks',
                'ordering': ['file', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['sponsor'], name='properties__sponsor_65a7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertychatsession',
            index=models.Index(fields=['property', 'user'], name='properties__propert_8f7fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfile',
            index=models.Index(fields=['property', 'category'], name='properties__propert_d5ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfile',
            index=models.Index(fields=['uploaded_by'], name='properties__uploade_8f47a2_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyfilechunk',
            index=models.Index(fields=['file', 'chunk_index'], name='properties__file_id_c3b985_idx'),
        ),
    ]
