# Generated by Django 6.1 on 2026-08-25 11:56

import django.db.models.deletion
import memorandums.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memorandum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Generating", "Generating"),
                            ("Draft", "Draft"),
                            ("Failed", "Failed"),
                            ("Published", "Published"),
                        ],
                        default="Generating",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("Editor", "Editor"), ("Preview", "Preview")],
                        default="Editor",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorandums",
                        to="properties.property",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorandums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Memorandum",
                "verbose_name_plural": "Memorandums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemorandumSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("property_information", "Property Information"),
                            ("executive_summary", "Executive Summary"),
                            ("property_overview", "Property Overview"),
                            ("property_highlights", "Property Highlights"),
                            ("area_overview", "Area Overview"),
                            ("area_highlights", "Area Highlights"),
                            ("market_summary", "Market Summary"),
                            ("financing_summary", "Financing Summary"),
                            ("financial_analysis", "Financial Analysis"),
                            ("sales_comparables", "Sales Comparables"),
                            ("lease_comparables", "Lease Comparables"),
                            ("area_amenities", "Area Amenities"),
                            ("sponsorship", "Sponsorship"),
                            ("disclaimer", "Disclaimer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[("text", "Text"), ("table", "Table")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("table_data", models.JSONField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=memorandums.models.section_image_upload_path,
                    ),
                ),
                ("order", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "memorandum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="memorandums.memorandum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memorandum Section",
                "verbose_name_plural": "Memorandum Sections",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="memorandum",
            index=models.Index(
                fields=["property", "sponsor"], name="memorandums_propert_4e42c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memorandum",
            index=models.Index(fields=["status"], name="memorandums_status_f61c1f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="memorandumsection",
            unique_together={("memorandum", "section_key")},
        ),
    ]
