# Generated by Django 6.1 on 2026-08-26 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_emails_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, the user receives emails for loan quote updates (new quote, accepted, declined).",
                    ),
                ),
                (
                    "marketing_emails_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, the user receives marketing and platform updates.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MEMORANDUM_GENERATED", "Memorandum Generated"),
                            ("LOAN_REQUEST_CREATED", "Loan Request Created"),
                            ("LOAN_REQUEST_UPDATED", "Loan Request Updated"),
                            ("QUOTE_SUBMITTED", "Quote Submitted"),
                            ("QUOTE_ACCEPTED", "Quote Accepted"),
                            ("QUOTE_DECLINED", "Quote Declined"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("memorandum_id", models.IntegerField(blank=True, null=True)),
                ("loan_request_id", models.IntegerField(blank=True, null=True)),
                ("quote_id", models.IntegerField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                ],
            },
        ),
    ]
